version: "3.7"

services:
  flue:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./.data/node-red/data:/data
      - .:/usr/src/node-red/flue
