version: "3.7"

services:
  flue:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./.data/node-red/data:/data
      - .:/usr/src/node-red/flue
